

INSERT INTO USER (USER_ID, USER_NAME, USER_LIMIT_CREDIT, USER_RISK, USER_INTEREST)
VALUES (1,'USER A',1000.00,'A', 10.25);


INSERT INTO USER (USER_ID, USER_NAME, USER_LIMIT_CREDIT, USER_RISK, USER_INTEREST)
VALUES (2,'USER B',1000.00,'B', 15.50);

INSERT INTO USER (USER_ID, USER_NAME, USER_LIMIT_CREDIT, USER_RISK, USER_INTEREST)
VALUES (3,'USER C',1000.00,'C', 18.75);
