

DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
	USER_ID IDENTITY PRIMARY KEY,
	USER_NAME VARCHAR2(50) NOT NULL,
	USER_LIMIT_CREDIT NUMBER NOT NULL,
	USER_RISK VARCHAR2(200) NOT NULL,
	USER_INTEREST NUMBER NOT NULL,

);
